resource_registry:

  OS::TripleO::Controller::PreNetworkConfig: file:///usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml

  OS::TripleO::Compute::PreNetworkConfig: file:///usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml

  OS::TripleO::ComputeOvsDpdk::PreNetworkConfig: file:///usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml
  OS::TripleO::BlockStorage::PreNetworkConfig: file:///usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml

  OS::TripleO::ObjectStorage::PreNetworkConfig: file:///usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml

  OS::TripleO::CephStorage::PreNetworkConfig: file:///usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml


#parameter_defaults:
  # Note: There are no global parameters which can be applied to all roles as
  # these configuration have to be specific to role.

  # Sample parameters for Compute and ComputeOvsDpdk roles
  #ComputeParameters:
    #KernelArgs: ""
    #TunedProfileName: ""
    #IsolCpusList: ""
  #ComputeOvsDpdkParameters:
    #KernelArgs: "intel_iommu=on iommu=pt default_hugepagesz=1GB hugepagesz=1G hugepages=60"
    #TunedProfileName: "cpu-partitioning"
    #IsolCpusList: ""
